version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-lab"
s3_bucket = "sam-app-images-us-east-1-447855955"
s3_prefix = "sam-lab"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
